# Generated by Django 4.2.10 on 2024-07-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_organizer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='subclass_level',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], null=True),
        ),
    ]
