# Generated by Django 4.2.10 on 2024-07-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_organizer_app', '0003_alter_character_subclass_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dnd_organizer_app.campaign'),
        ),
    ]
